name: sensors_vkr
description: sensors checker
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  sensors_plus: ^2.0.4
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  dio: ^5.1.1
  get: ^4.6.5
  flutter_barometer: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true